### PR TITLE
make pipeline run smooth

### PR DESCRIPTION
**Pull request by riezebosch**
Screenshot 2023-10-10 at 14 14 36

### CODE REVIEW

**Comment by dichternebel** [comment]
Löblich! Hier werden noch die wirklich wichtigen Projekte geforked! ;-)

**Comment by riezebosch** [comment]
@tschissler @p-goetz ?! now doesn't work when cloning a new repo from this template.

**Comment by tschissler** [comment]
@riezebosch Not sure why it does not work for you. I just retriggered the pipeline for this repo and it seems to work just fine (see the build badge on the readme).
When changing the pipeline to ubuntu, most students will not be able to run the app from the drop location as the majority is on Windows. I would suggest that we can do a cross-plattform build and provide self-contained deployments for WIndows and Linux. But that will lengthen the duration of the pipeline if the trainer has not enough parallel agent licenses.

**Comment by riezebosch** [comment]
a) that's probably since this repository was created before the permissions were implemented. Try it on a new repository created from this template.

b) you can perfectly run a dotnet application on Windows that is compiled on Ubuntu and vice versa. As long as the .NET runtime (or SDK, which includes the runtime) is installed. As long as you don't compile it to a specific target platform, as it is right now...

I can split both commits and create separate pull requests if you like.

**Comment by tschissler** [comment]
a) I do import it in Azure DevOps for my trainings, this is maybe why I have not come across this issue yet :-)
b) I will have to investigate this more but during my previous experiments I had the impression that you cannot build self-contained exe for Windows on Linux. I will check later this week.

**Comment by riezebosch** [comment]
b) [I think you are correct](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/cross-compile), I never bothered building self-contained executables for this training.

**Comment by riezebosch** [comment]
@tschissler ☝🏻 I updated the pull request to only have the permission fix and not the run on ubuntu change.

**Comment by tschissler** [comment]
Approved :-)

**Pull request merged**
